fix: P0 - remove 8 stray None args in register() calls
TypeError: register() takes 1 positional argument but 2 were given
would crash at module load. All register(name, None, permission=...)
changed to register(name, permission=...).